from pydantic import BaseModel
from sqlalchemy import Column, Integer, String, ForeignKey
from database import Base

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True)
    hashed_password = Column(String)     # Generated by the passlib library

class Secret(Base):
    __tablename__ = "secrets"
    id = Column(Integer, primary_key=True, index=True)
    key_name = Column(String)
    encrypted_value = Column(String)     # The actual secret
    encrypted_data_key = Column(String)  # The key needed to unlock the secret
    owner_id = Column(Integer, ForeignKey("users.id"))

# --- Add these Pydantic Models for the API ---
class UserCreate(BaseModel):
    username: str
    password: str

class SecretCreate(BaseModel):
    key_name: str
    value: str